# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='creat_part', kernelFunction='creat_part', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='name', keyword='name', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='length', keyword='length', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='width', keyword='width', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='height', keyword='height', default='')
dialogBox.show()